### ISSUE TITLE
Return all ContentValues from relation

### ISSUE THREAD

**Issue by sgrekov** [maskarade/Android-Orma#416]
It would be useful to have generated method in <Model>_Relation, which will return all content values for particular model, like it made in upsertWithoutTransaction method, 
something like
public abstract ContentValues allValues(@NonNull final Model model);

It will be useful when we manually check for local value and depending on result, call insert or update.

**Comment by gfx** [comment]
Seems good. Will try it in the next version.

**Comment by sgrekov** [comment]
Thanks! Looking forward to this improvement.
