### ISSUE TITLE
AndroidX support

### ISSUE THREAD

**Issue by k-kagurazaka** [maskarade/Android-Orma#447]
[AndroidX stable has been released.](https://developer.android.com/topic/libraries/support-library/androidx-rn#1.0.0)

I think it's important to migrate support library to AndroidX.
We have two options to do;

- Switch dependency by whether a user is using AndroidX or not.
  - Pros. / Users can use new features of Orma whether to use AndroidX or not.
  - Cons. / Users must enable Jetifier. It is very buggy and negatively affects build time.
- A new major version (v6.x) only supports AndroidX.
  - Pros. / Code become simple and Jetifier is not needed.
  - Cons. / Users must migrate to AndroidX to use latest version of Orma.

I prefer the latter option,  @gfx whats your opinion on this?

**Comment by gfx** [comment]
It is absolutely the second, i.e. upgrading the major version in order to heavily reduce both the efforts of committers and users.

**Comment by k-kagurazaka** [comment]
Thank you for your opinion.
I'm going to send two pull requests for the issue.
