### ISSUE TITLE
A link to expired methodscount.com domain is in README

### ISSUE THREAD

**Issue by muojp** [maskarade/Android-Orma#474]
I just noticed the link to methodscount.com in README is broken. It seems the domain expired in Oct-2018 and I also found a statement by the author sunsetting the service: [Sunsetting MethodsCount.com](https://medium.com/@rotxed/sunsetting-methodscount-com-cb5693a9586).

I Googled a bit looking for alternative web-services or handy Docker image of the [FOSS version](https://github.com/dextorer/MethodsCount) but no luck.

Perhaps we may integrate [dexcount-gradle-plugin](https://github.com/KeepSafe/dexcount-gradle-plugin) into CI process and get methods-count automatically on releases, but, well, it looks like a bit overkill for me.

So I suggest removing the _Method Count_ paragraph from README.

**Comment by gfx** [comment]
Thanks.

I won't find alternatives for Orma; method counts to artifacts are not so useful anyway because it is the generated methods that increase the method count of APKs that use Orma.
